# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMi
  
  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxDataSources'
  
  # Network
  pod 'Alamofire'

  target 'MVVMiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMiUITests' do
    # Pods for testing
  end

end
